version: '3.7'

services:
    SQL2019:
        image: beard2019image
        ports:  
          - "15592:1433"
        networks: 
          - BeardsMagicNetwork
    SQL2019-1:
        image: beard2019image
        ports:  
          - "15593:1433"
        networks: 
          - BeardsMagicNetwork
networks: 
  BeardsMagicNetwork: